export const STRINGS = {
    ru: {
        app_title: "Cloud Defender",
        action_close: "Закрыть",
        action_cancel: "Отмена",
        action_save: "Сохранить",
        action_saving: "Сохраняем...",
        action_create: "Создать",
        action_remove: "Удалить",
        action_refresh: "Обновить",
        action_hide: "Скрыть",
        toolbar_refresh_aria: "Обновить список",
        dialog_ok: "Ок",
        dialog_error: "Ошибка",
        dialog_delete_title: "Удаление",
        dialog_delete: "Удалить",
        dialog_cancel: "Отмена",
        dialog_confirm: "Подтвердить",
        dialog_close: "Закрыть",
        dialog_create: "Создать",
        dialog_select: "Выбрать",
        dialog_continue: "Продолжить",
        dialog_understood: "Понятно",
        dialog_done_title: "Готово",
        action_create_folder: "Создать папку",
        action_upload_file: "Загрузить файл",
        action_upload_folder: "Загрузить папку",
        action_upload_files: "Загрузить файлы",

        table_name: "Имя",
        table_size: "Размер",
        table_modified: "Изменено",
        table_empty: "Здесь пока пусто",
        table_loading: "Загрузка...",
        default_storage_name: "Хранилище",

        menu_open: "Открыть",
        menu_download: "Скачать",
        menu_download_zip: "Скачать как zip",
        menu_download_selected: "Скачать выбранное (zip)",
        menu_rename: "Переименовать",
        menu_move: "Переместить",
        menu_copy: "Копировать",

        dialog_rename_title: "Переименовать",
        dialog_rename_message: "Введите новое имя",
        dialog_rename_placeholder: "Новое имя",
        dialog_new_folder_title: "Новая папка",
        dialog_new_folder_message: "Введите название папки",
        dialog_new_folder_placeholder: "Имя папки",
        folder_create_error: "Не удалось создать папку",
        dialog_delete_many: "Удалить {count} объектов безвозвратно?",
        dialog_delete_one: 'Удалить "{name}"?',

        storage_title: "Хранилище",
        storage_list_title: "Хранилища",
        storage_list_heading: "Хранилища",
        connected_as: "Подключены как",
        storage_connecting: "Подключаемся...",
        storage_loading_message: "Подключаемся...",
        storage_none: "Хранилища отсутствуют",
        storage_add: "Добавить хранилище",
        storage_change_password: "Изменить пароль шифрования",
        storage_delete: "Удалить",
        storage_delete_title: "Удалить хранилище",
        storage_delete_question: 'Вы уверены, что хотите удалить "{name}"?',
        storage_change_password_title: "Смена пароля шифрования",
        storages_delete_confirm: "Удалить хранилище",
        storages_delete_question: 'Вы уверены, что хотите удалить "{name}"?',
        delete_cancel: "Отмена",
        delete_busy: "Удаляем...",
        delete_confirm: "Удалить",

        connect_spinner_creating: "Создаем шифрование",
        connect_spinner_init: "Инициализация",
        connect_spinner_loading: "Подключаем хранилище",

        rclone_keys_title: "Ключи для rclone",
        rclone_keys_loading: "Загрузка...",
        rclone_error: "Не удалось получить ключи",

        change_password_title: "Смена пароля",
        change_password_encryption_title: "Смена пароля шифрования",
        change_password_encryption_error: "Не удалось сменить пароль шифрования",
        change_password_error: "Не удалось сменить пароль",
        field_current_password: "Текущий пароль",
        field_new_password: "Новый пароль",
        field_confirm: "Подтверждение",
        error_fill_all: "Заполните все поля",
        error_password_mismatch: "Пароли не совпадают",
        password_changed_ok: "Пароль обновлен",
        encryption_password_changed_ok: "Пароль шифрования обновлен",

        account_section_title: "Учетная запись",
        account_change_password: "Сменить пароль",
        account_export_rclone: "Получить ключи для rclone",
        account_logout: "Выйти",

        transfer_title: "Передачи",
        transfer_header_title: "Передачи файлов",
        transfer_header_caption: "Загрузки в Drive и скачивания на устройство",
        transfer_summary_active: "{count} активно",
        transfer_summary_total: "{count} элементов",
        transfer_collapse: "Свернуть",
        transfer_expand: "Развернуть",
        transfer_close: "Закрыть",
        transfer_hide: "Скрыть",
        transfer_uploads: "Загрузки",
        transfer_downloads: "Скачивания",
        transfer_clear_finished: "Очистить завершенные",
        transfer_label_in_progress: "В процессе",
        transfer_label_failed: "Не удалось",
        transfer_label_partial_done: "Частично завершено",
        transfer_label_partial_cancel: "Частично отменено",
        transfer_label_done: "Готово",
        transfer_label_cancelled: "Отменено",
        transfer_meta_files: "Файлы {done}/{total}",
        transfer_meta_progress: "Прогресс {percent}%",
        transfer_meta_eta: "Осталось ~{eta}",
        transfer_meta_errors: "Ошибки {count}",
        transfer_meta_cancelled: "Отменено {count}",
        transfer_group_default: "Сеанс загрузки",
        transfer_task_untitled: "Без названия",
        transfer_subtitle_folder: "Папка (zip)",
        transfer_subtitle_file: "Файл",
        transfer_integrity_error: "Нарушена целостность данных",
        transfer_eta_label: "ETA {eta}",

        add_storage_title: "Новое хранилище",
        add_storage_add: "Добавить",
        add_storage_name: "Название",
        add_storage_root: "Корневой путь",
        add_storage_google_account: "Google аккаунт",
        add_storage_create: "Создать",
        add_storage_creating: "Создаем...",
        add_storage_choose_account: "Выбрать",
        add_storage_close: "Закрыть",
        add_storage_error_perms: "Не получены нужные права Google Drive",
        add_storage_error_google: "Не удалось получить разрешения Google аккаунта",
        add_storage_error_name: "Введите название хранилища",
        add_storage_error_root: "Корневой путь не должен начинаться или заканчиваться на /",
        add_storage_error_choose_account: "Выберите Google аккаунт",
        add_storage_error_create: "Не удалось создать хранилище",
        add_storage_submit: "Создать",

        auth_login_heading: "Войти",
        auth_login: "Войти",
        auth_username: "Логин",
        auth_password: "Пароль",
        auth_login_busy: "Входим...",
        auth_register_heading: "Создать учетную запись",
        auth_register_eyebrow: "Регистрация",
        auth_register_title: "Создать учетную запись",
        auth_register: "Создать аккаунт",
        auth_register_button: "Создать",
        auth_register_busy: "Создаем...",
        auth_register_cancel: "Отмена",
        auth_close: "Закрыть",
        auth_password_confirm: "Подтверждение пароля",
        auth_error_login: "Не удалось выполнить вход",
        auth_error_register_fill: "Заполните логин и пароль",
        auth_error_register_length: "Пароль должен быть не короче 8 символов",
        auth_error_register_mismatch: "Пароли не совпадают",
        auth_error_register: "Не удалось создать учетную запись",

        password_prompt_title_setup: "Создание пароля",
        password_prompt_setup_message: "Создайте пароль для шифрования файлов",
        password_prompt_title_unlock: "Требуется пароль",
        password_prompt_title_default: "Пароль",
        password_prompt_message_default: "Введите пароль",
        password_prompt_message_retry: "Неверный пароль. Попробуйте еще раз.",
        password_prompt_empty: "Пароль не может быть пустым",
        password_prompt_confirm_mismatch: "Пароли не совпадают",
        password_prompt_primary_required: "Основной пароль rclone обязателен",
        password_prompt_password_label: "Пароль",
        password_prompt_confirm_label: "Подтверждение пароля",
        password_prompt_placeholder: "Введите пароль",
        password_prompt_repeat_placeholder: "Повторите пароль",
        password_prompt_hide: "Скрыть",
        password_prompt_show: "Показать",
        password_required_init: "Требуется пароль для инициализации шифрования",
        password_required_unlock: "Требуется пароль для расшифровки ключа",
        password_required_encrypt: "Требуется пароль для шифрования ключа",
        password_required_configure: "Требуется пароль для настройки шифрования",
        password_prompt_primary_placeholder: "password из конфигурации rclone",
        password_prompt_secondary_label: "password2 (опционально)",
        password_prompt_secondary_placeholder: "password2 из конфигурации rclone",
        password_prompt_primary_label: "password",
        password_prompt_secondary_heading: "password2 (опционально)",
        password_prompt_encryption_mode: "Режим шифрования",
        password_prompt_mode_own: "Собственный алгоритм шифрования",
        password_prompt_encryption_algorithm: "Алгоритм шифрования",
        password_prompt_hash_algorithm: "Алгоритм хэширования",
        password_prompt_filename_title: "Как шифровать имена файлов",
        password_prompt_filename_encrypt: "Шифровать имена файлов",
        password_prompt_filename_obfuscate: "Простейшая обфускация имён",
        password_prompt_filename_off: "Не шифровать имена файлов",
        password_prompt_direnc_title: "Шифрование имён папок",
        password_prompt_direnc_on: "Шифровать имена папок",
        password_prompt_direnc_off: "Не шифровать имена папок",
        password_prompt_continue: "Продолжить",
        password_prompt_cancel: "Отмена",

        movecopy_title_move: "Переместить в выбранную папку",
        movecopy_title_copy: "Копировать в выбранную папку",
        movecopy_folder: "Папка",
        movecopy_root: "Корень",
        movecopy_no_folders: "Нет папок",
        movecopy_loading: "Загружаем...",
        movecopy_cancel: "Отмена",
        movecopy_close: "Закрыть",
        movecopy_move_here: "Переместить сюда",
        movecopy_copy_here: "Копировать сюда",
        movecopy_current_folder: "Текущая папка",

        storage_select_title: "Выберите хранилище",
        storage_select_empty: "Нет доступных хранилищ",
        storage_select_name: "Имя",
        storage_select_path: "Путь",
        storage_select_action: "Действие",
        storage_select_choose: "Выбрать",

        upload_overlay_queue: "В очереди",
        upload_overlay_init: "Инициализация",
        upload_overlay_uploading: "Загрузка",
        upload_overlay_done: "Готово",
        upload_overlay_cancelled: "Отменено",
        upload_overlay_error: "Ошибка",
        upload_overlay_partial_cancel: "Частично отменено",
        upload_overlay_partial_error: "Завершено с ошибками",
        upload_overlay_title: "Загрузка в Google Drive",
        upload_overlay_close: "Закрыть",
        upload_overlay_folder_label: "Папка",
        upload_overlay_cancel: "Отмена",
        upload_overlay_remove: "Удалить",
        integrity_error_message: "Нарушена целостность данных",
        upload_status_cancelled: "Отменено",
        upload_status_failed: "Загрузка не удалась",
        upload_error_crypto_required: "Требуется cryptoApi",

        folder_uploader_title_unavailable: "Загрузка папок недоступна",
        folder_uploader_msg_unavailable:
            "Браузер не поддерживает выбор папки. Используйте Chrome или Edge, либо перетащите папку на страницу.",
        folder_uploader_understood: "Понятно",
        folder_uploader_title_failed: "Не удалось подготовить загрузку",
        folder_uploader_close: "Закрыть",
        folder_uploader_cancel: "Отмена",
        folder_uploader_button: "Загрузить папку",

        drop_hint: "Отпусти файлы или папки, чтобы загрузить в Google Drive",

        downloadmgr_big_folder_title: "Большая папка",
        downloadmgr_big_folder_message: "Папка весит примерно {mb} МБ. Скачать как архив?",
        downloadmgr_big_folder_confirm: "Скачать",
        downloadmgr_no_direct_title: "Нет прямого сохранения",
        downloadmgr_no_direct_message:
            "Файл около {mb} МБ будет загружен через память браузера. Продолжить?",

        api_login_error: "Не удалось выполнить вход",
        api_register_error: "Не удалось создать учетную запись",
        api_change_pwd_error: "Не удалось сменить пароль",
        api_fetch_rclone_error: "Не удалось получить ключи для rclone",
        storages_error_fetch: "Не удалось получить список хранилищ",
        storages_error_create: "Не удалось создать хранилище",
        storages_error_delete: "Не удалось удалить хранилище",
        storages_error_refresh: "Не удалось обновить токен хранилища",
        storages_error_prepare: "Не удалось подготовить хранилище",
        storages_error_load: "Не удалось загрузить хранилища",
        drive_error_folder: "Не удалось загрузить содержимое папки",

        file_alt_folder: "Папка",
        file_alt_file: "Файл",
        aria_menu: "Меню",
        aria_select_all: "Выбрать все",
        aria_google_status: "Статус Google",
        busy_overlay_wait: "Пожалуйста, подождите…",
    },
    en: {
        app_title: "Cloud Defender",
        action_close: "Close",
        action_cancel: "Cancel",
        action_save: "Save",
        action_saving: "Saving...",
        action_create: "Create",
        action_remove: "Delete",
        action_refresh: "Refresh",
        action_hide: "Hide",
        toolbar_refresh_aria: "Refresh list",
        dialog_ok: "OK",
        dialog_error: "Error",
        dialog_delete_title: "Delete",
        dialog_delete: "Delete",
        dialog_cancel: "Cancel",
        dialog_confirm: "Confirm",
        dialog_close: "Close",
        dialog_create: "Create",
        dialog_select: "Select",
        dialog_continue: "Continue",
        dialog_understood: "Got it",
        dialog_done_title: "Done",
        action_create_folder: "Create folder",
        action_upload_file: "Upload file",
        action_upload_folder: "Upload folder",
        action_upload_files: "Upload files",

        table_name: "Name",
        table_size: "Size",
        table_modified: "Modified",
        table_empty: "Nothing here yet",
        table_loading: "Loading...",
        default_storage_name: "Storage",

        menu_open: "Open",
        menu_download: "Download",
        menu_download_zip: "Download as zip",
        menu_download_selected: "Download selected (zip)",
        menu_rename: "Rename",
        menu_move: "Move",
        menu_copy: "Copy",

        dialog_rename_title: "Rename",
        dialog_rename_message: "Enter new name",
        dialog_rename_placeholder: "New name",
        dialog_new_folder_title: "New folder",
        dialog_new_folder_message: "Enter folder name",
        dialog_new_folder_placeholder: "Folder name",
        folder_create_error: "Failed to create folder",
        dialog_delete_many: "Delete {count} items permanently?",
        dialog_delete_one: 'Delete "{name}"?',

        storage_title: "Storage",
        storage_list_title: "Storages",
        storage_list_heading: "Storages",
        connected_as: "Connected as",
        storage_connecting: "Connecting...",
        storage_loading_message: "Connecting...",
        storage_none: "No storages available",
        storage_add: "Add storage",
        storage_change_password: "Change encryption password",
        storage_delete: "Delete",
        storage_delete_title: "Delete storage",
        storage_delete_question: 'Are you sure you want to delete "{name}"?',
        storage_change_password_title: "Change encryption password",
        storages_delete_confirm: "Delete storage",
        storages_delete_question: 'Are you sure you want to delete "{name}"?',
        delete_cancel: "Cancel",
        delete_busy: "Deleting...",
        delete_confirm: "Delete",

        connect_spinner_creating: "Creating encryption",
        connect_spinner_init: "Initializing",
        connect_spinner_loading: "Connecting storage",

        rclone_keys_title: "Keys for rclone",
        rclone_keys_loading: "Loading...",
        rclone_error: "Failed to fetch keys",

        change_password_title: "Change password",
        change_password_encryption_title: "Change encryption password",
        change_password_encryption_error: "Failed to change encryption password",
        change_password_error: "Failed to change password",
        field_current_password: "Current password",
        field_new_password: "New password",
        field_confirm: "Confirmation",
        error_fill_all: "Fill in all fields",
        error_password_mismatch: "Passwords do not match",
        password_changed_ok: "Password updated",
        encryption_password_changed_ok: "Encryption password updated",

        account_section_title: "Account",
        account_change_password: "Change password",
        account_export_rclone: "Export keys for rclone",
        account_logout: "Log out",

        transfer_title: "Transfers",
        transfer_header_title: "File transfers",
        transfer_header_caption: "Uploads to Drive and downloads to device",
        transfer_summary_active: "{count} active",
        transfer_summary_total: "{count} items",
        transfer_collapse: "Collapse",
        transfer_expand: "Expand",
        transfer_close: "Close",
        transfer_hide: "Hide",
        transfer_uploads: "Uploads",
        transfer_downloads: "Downloads",
        transfer_clear_finished: "Clear finished",
        transfer_label_in_progress: "In progress",
        transfer_label_failed: "Failed",
        transfer_label_partial_done: "Partially done",
        transfer_label_partial_cancel: "Partially cancelled",
        transfer_label_done: "Done",
        transfer_label_cancelled: "Cancelled",
        transfer_meta_files: "Files {done}/{total}",
        transfer_meta_progress: "Progress {percent}%",
        transfer_meta_eta: "ETA ~{eta}",
        transfer_meta_errors: "Errors {count}",
        transfer_meta_cancelled: "Cancelled {count}",
        transfer_group_default: "Upload batch",
        transfer_task_untitled: "Untitled",
        transfer_subtitle_folder: "Folder (zip)",
        transfer_subtitle_file: "File",
        transfer_integrity_error: "Data integrity corrupted",
        transfer_eta_label: "ETA {eta}",

        add_storage_title: "New storage",
        add_storage_add: "Add",
        add_storage_name: "Name",
        add_storage_root: "Root path",
        add_storage_google_account: "Google account",
        add_storage_create: "Create",
        add_storage_creating: "Creating...",
        add_storage_choose_account: "Choose",
        add_storage_close: "Close",
        add_storage_error_perms: "Required Google Drive permissions not granted",
        add_storage_error_google: "Failed to obtain Google account permissions",
        add_storage_error_name: "Enter storage name",
        add_storage_error_root: "Root path must not start or end with /",
        add_storage_error_choose_account: "Choose a Google account",
        add_storage_error_create: "Failed to create storage",
        add_storage_submit: "Create",

        auth_login_heading: "Log in",
        auth_login: "Log in",
        auth_username: "Username",
        auth_password: "Password",
        auth_login_busy: "Logging in...",
        auth_register_heading: "Create account",
        auth_register_eyebrow: "Register",
        auth_register_title: "Create an account",
        auth_register: "Create account",
        auth_register_button: "Create",
        auth_register_busy: "Creating...",
        auth_register_cancel: "Cancel",
        auth_close: "Close",
        auth_password_confirm: "Confirm password",
        auth_error_login: "Login failed",
        auth_error_register_fill: "Enter username and password",
        auth_error_register_length: "Password must be at least 8 characters",
        auth_error_register_mismatch: "Passwords do not match",
        auth_error_register: "Failed to create account",

        password_prompt_title_setup: "Create password",
        password_prompt_setup_message: "Create a password for file encryption",
        password_prompt_title_unlock: "Password required",
        password_prompt_title_default: "Password",
        password_prompt_message_default: "Enter password",
        password_prompt_message_retry: "Incorrect password. Try again.",
        password_prompt_empty: "Password cannot be empty",
        password_prompt_confirm_mismatch: "Passwords do not match",
        password_prompt_primary_required: "Primary rclone password is required",
        password_prompt_password_label: "Password",
        password_prompt_confirm_label: "Confirm password",
        password_prompt_placeholder: "Enter password",
        password_prompt_repeat_placeholder: "Repeat password",
        password_prompt_hide: "Hide",
        password_prompt_show: "Show",
        password_required_init: "Password is required to initialize crypto configuration",
        password_required_unlock: "Password is required to unlock encryption key",
        password_required_encrypt: "Password is required to encrypt key",
        password_required_configure: "Password is required to configure crypto",
        password_prompt_primary_placeholder: "password from rclone config",
        password_prompt_secondary_label: "password2 (optional)",
        password_prompt_secondary_placeholder: "password2 from rclone config (optional)",
        password_prompt_primary_label: "password",
        password_prompt_secondary_heading: "password2 (optional)",
        password_prompt_encryption_mode: "Encryption mode",
        password_prompt_mode_own: "Client-side encryption",
        password_prompt_encryption_algorithm: "Encryption algorithm",
        password_prompt_hash_algorithm: "Hash algorithm",
        password_prompt_filename_title: "How to encrypt the filenames.",
        password_prompt_filename_encrypt: "Encrypt the filenames",
        password_prompt_filename_obfuscate: "Very simple filename obfuscation",
        password_prompt_filename_off: "Don't encrypt the file names",
        password_prompt_direnc_title: "Encrypt directory name",
        password_prompt_direnc_on: "Encrypt directory names",
        password_prompt_direnc_off: "Don't encrypt directory names, leave them intact.",
        password_prompt_continue: "Continue",
        password_prompt_cancel: "Cancel",

        movecopy_title_move: "Move to selected folder",
        movecopy_title_copy: "Copy to selected folder",
        movecopy_folder: "Folder",
        movecopy_root: "Root",
        movecopy_no_folders: "No folders",
        movecopy_loading: "Loading...",
        movecopy_cancel: "Cancel",
        movecopy_close: "Close",
        movecopy_move_here: "Move here",
        movecopy_copy_here: "Copy here",
        movecopy_current_folder: "Current folder",

        storage_select_title: "Choose a storage",
        storage_select_empty: "No storages available",
        storage_select_name: "Name",
        storage_select_path: "Path",
        storage_select_action: "Action",
        storage_select_choose: "Select",

        upload_overlay_queue: "In queue",
        upload_overlay_init: "Initializing",
        upload_overlay_uploading: "Uploading",
        upload_overlay_done: "Done",
        upload_overlay_cancelled: "Cancelled",
        upload_overlay_error: "Error",
        upload_overlay_partial_cancel: "Partially cancelled",
        upload_overlay_partial_error: "Finished with errors",
        upload_overlay_title: "Upload to Google Drive",
        upload_overlay_close: "Close",
        upload_overlay_folder_label: "Folder",
        upload_overlay_cancel: "Cancel",
        upload_overlay_remove: "Remove",
        integrity_error_message: "Data integrity corrupted",
        upload_status_cancelled: "Cancelled",
        upload_status_failed: "Upload failed",
        upload_error_crypto_required: "cryptoApi is required",

        folder_uploader_title_unavailable: "Folder upload unavailable",
        folder_uploader_msg_unavailable:
            "Your browser does not support folder selection. Use Chrome or Edge, or drop a folder onto the page.",
        folder_uploader_understood: "Got it",
        folder_uploader_title_failed: "Failed to prepare upload",
        folder_uploader_close: "Close",
        folder_uploader_cancel: "Cancel",
        folder_uploader_button: "Upload folder",

        drop_hint: "Drop files or folders to upload to Google Drive",

        downloadmgr_big_folder_title: "Large folder",
        downloadmgr_big_folder_message: "Folder is about {mb} MB. Download as archive?",
        downloadmgr_big_folder_confirm: "Download",
        downloadmgr_no_direct_title: "Direct download unavailable",
        downloadmgr_no_direct_message: "File about {mb} MB will be loaded through browser memory. Continue?",

        api_login_error: "Login failed",
        api_register_error: "Registration failed",
        api_change_pwd_error: "Failed to change password",
        api_fetch_rclone_error: "Failed to fetch rclone keys",
        storages_error_fetch: "Failed to fetch storages",
        storages_error_create: "Failed to create storage",
        storages_error_delete: "Failed to delete storage",
        storages_error_refresh: "Failed to refresh storage token",
        storages_error_prepare: "Failed to prepare storage",
        storages_error_load: "Failed to load storages",
        drive_error_folder: "Failed to load folder contents",

        file_alt_folder: "Folder",
        file_alt_file: "File",
        aria_menu: "Menu",
        aria_select_all: "Select all",
        aria_google_status: "Google status",
        busy_overlay_wait: "Please wait…",
    },
};

export const DEFAULT_LANG = "ru";

export function t(key, fallback) {
    const table = STRINGS[DEFAULT_LANG] || {};
    if (Object.prototype.hasOwnProperty.call(table, key)) {
        return table[key];
    }
    const enFallback = STRINGS.en?.[key];
    if (enFallback) return enFallback;
    if (fallback) return fallback;
    return key;
}
